### ISSUE TITLE
When new transactions are ready to sign highlight the entire transaction row vs. the corner of the transaction

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#864] opened 2024-09-04 21:22 UTC
### Problem

The transaction row is colored with red on the top left of the transaction. 

### Solution

Update to color the entire transaction row to a light/faint red for those that have not been seen by the user.

**Comment by SvetBorislavov** [comment] 2024-12-04 13:56
@SimiHunjan  Duplicate of #933

**Closed by SvetBorislavov** 2024-12-04 13:56 UTC
